### ISSUE TITLE
Garrybrayn

### ISSUE THREAD

**Issue by MK-ATMOSFERA** [near/near-sdk-rs#1193]
> https://github.com/near/near-sdk-rs/blob/8a908c30ce43fbf1b1866486668a647fbc28b5bd/near-sdk/src/store/mod.rs#L84-L90
The background color is `#ffffff` for light mode and `#000000` for dark mode.
[1064900.txt.csv](https://github.com/user-attachments/files/15586171/1064900.txt.csv)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-sdk-rs/pull/1192
- [ ] https://github.com/near/near-sdk-rs/issues/1188
- [ ] https://github.com/near/near-sdk-rs/pull/1191
- [ ] https://github.com/near/near-sdk-rs/pull/1189
- [ ] https://github.com/near/near-sdk-rs/pull/1185
- [ ] https://github.com/near/near-sdk-rs/issues/1190
- [ ] https://github.com/near/near-sdk-rs/pull/1186
- [ ] https://github.com/near/near-sdk-rs/pull/1165
- [ ] https://github.com/near/near-sdk-rs/issues/1200
```

**Comment by MK-ATMOSFERA** [comment]
[https://explorer.aurora.dev/token/0x1FaD1C94E622f892a3F29796f9981D89571974c5]
![Uploading 01003o3i-c6a1_870x400.jpeg…]()
