### ISSUE TITLE
doc: move doc of non-deprecated macros from `near-sdk-macros` to reexport in `near-sdk` for continuous validation in ci

### ISSUE THREAD

**Issue by dj8yfo** [near/near-sdk-rs#1288]
documentation of all non-deprecated items of `near-sdk-macros` should be transferred to documentation
over re-export in `near-sdk`, e.g. https://github.com/near/near-sdk-rs/blob/master/near-sdk-macros/src/lib.rs#L46-L96 should be moved to near-sdk/src/lib.rs

```rust
/// ....
/// ...
pub use near_sdk_macros::near;
```
all 
````
/// ```ignore
````
should be replaced with 
````
/// ```no_run
````
or 
````
/// ```rust
````

because it will allow to continuously check api, proposed in docs, for correctness in ci via test job https://github.com/near/near-sdk-rs/blob/master/.github/workflows/test.yml#L43 . 

Doc in `near-sdk-macros` for these items will be empty (or a little msg with separator can be thrown in https://github.com/near/borsh-rs/pull/326/commits/46d7f653bd44ce2708031414a41f75a9c69d3d14)
![image](https://github.com/user-attachments/assets/73e59ae0-6327-4eb3-8c1e-e6a3e64dd810)
but it will be in `near` crate: 
![image](https://github.com/user-attachments/assets/ba88e97f-c247-4acc-920d-133bc52ca172)

```[tasklist]
### Tasks
- [ ] near_sdk_macros::ext_contract
- [ ] near_sdk_macros::near
- [ ] near_sdk_macros::near_bindgen
- [ ] near_sdk_macros::BorshStorageKey
- [ ] near_sdk_macros::EventMetadata
- [ ] near_sdk_macros::FunctionError
- [ ] near_sdk_macros::NearSchema
- [ ] near_sdk_macros::PanicOnDefault
- [ ] add BIG BIG HIGHLIGHTED link from QuickStart section, leading to `#[near]` documentation
```

**Comment by dj8yfo** [comment]
mentioned above as one of subtasks
![image](https://github.com/user-attachments/assets/7fc17543-2851-425e-9ecd-04eadee62434)
