### ISSUE TITLE
doc: move body of examples from `near` (gated under `__macro_docs` feature) module to `#[near]` macro doc (with link)

### ISSUE THREAD

**Issue by dj8yfo** [near/near-sdk-rs#1289]
Body of all sub-attributes/annotations docs in https://docs.rs/near-sdk/5.7.0/near_sdk/near/index.html has 
to be moved to documentation of https://docs.rs/near-sdk/5.7.0/near_sdk/attr.near.html , 
and links to new place left via `#anchors`

using https://github.com/rust-lang/rust/issues/62833

```rust
/// See [`near_sdk::near #[init]`](macro@crate::near#init-sub-attribute)
```

![image](https://github.com/user-attachments/assets/b462350c-05db-4265-bab2-9be6f0d723a4)

Thus individual sub-attributes/annotations will remain searchable
![image](https://github.com/user-attachments/assets/8559d0b4-bea0-47a1-a723-5e9676e18acb)

but the documentation for all about `#[near]` macro will be on https://docs.rs/near-sdk/5.7.0/near_sdk/attr.near.html page

```[tasklist]
### Tasks
- [ ] module has to be renamed from `near` to `near_annotations` as it conflicts with `#[near]` top item, that's why macro@crate is needed above
- [ ] near_sdk::near_annotations::handle_result
- [ ] near_sdk::near_annotations::init
- [ ] near_sdk::near_annotations::payable
- [ ] near_sdk::near_annotations::private
- [ ] near_sdk::near_annotations::result_serializer
- [ ] near_sdk::near_annotations::event_json  (??, not present yet)
- [ ] near_sdk::near_annotations::contract_metadata (??, not present yet)
```

**Comment by dj8yfo** [comment]
this in conjunction with #1288 might improve overall structure of rustdocs regarding `#[near]` macro, 
allowing to keep it up-to-date and possibly adding other, yet undocumented sub-attributes

**Comment by dj8yfo** [comment]
this is mutually exclusive with https://github.com/near/near-sdk-rs/issues/1287, so closing #1287
