### ISSUE TITLE
near-sdk-sim cli that covers functionality of vm standalone for contract dev

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-rs#381]
As discussed with @nearmax vm runner standalone is going to be depreicate in favor of near-sdk-sim. As of now near-sdk-sim cannot cover all vm runner standalone usage. These missing functionaliies are addressed in different PRs, this issue is specifically near-sdk-sim should provide a CLI interface, so that developer doesn't need to write code to invoke simulator reproduce and diagnose gas usage of a testnet transaction execution.

Requirements:

*   [ ] near-sdk-sim cli can run a contract function call, given state, contract code, caller, method name, args, etc.
*   [ ] cli can help download state from rpc, and organize in a format that can be load in sim as state_records: [https://github.com/near/repro-near-funcall/blob/master/collect-state-records.js](https://github.com/near/repro-near-funcall/blob/master/collect-state-records.js)
*   [ ] cli can also help download block info from rpc, and organize in a format that can be load as genesis config, so info like block_height, epoch_height etc. is correctly matched, since some contract function logic use block_height etc. so we have to have them in reproduce
*   [ ] unlike vm standalone, it should be able to execute cross contract call
