### ISSUE TITLE
Rust SDK 4.0 stabilization tracker

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#494]
Probably a good idea to keep track of things we want to be sure of before the 4.0 release:
- [x] #491 
- [x] #492 
- [x] Borsh to 0.9, which would require releases of VM logic crates (to avoid duplicate deps for tests) #476 #500 https://github.com/near/nearcore/issues/4603 #639 
- [x] Resolution on #263 so this doesn't keep getting pushed back?
- [x] Switch storage keys to `Box<[u8]>`?
- [x] #495 
- [x] #497 
- [x] #498 
- [x] ~~Resolution on #526~~ (API will be changed for next major release)
- [x] #527 
- [x] #521 
- [x] #520
- [x] https://github.com/near/nearcore/pull/4732 (license updates, remove gpl3 requirement from SDK)
- [x] #740 #742 
- [x] https://github.com/near/near-sdk-rs/issues/813
- [x] https://github.com/near/near-sdk-rs/issues/802 https://github.com/near/near-sdk-rs/pull/817

Feel free to add anything else relevant or thoughts on these!

**Comment by robert-zaremba** [comment]
Any ETA for the release?

**Comment by austinabell** [comment]
> Any ETA for the release?

Hard to give a good estimate for ETA, as is it dependant on a few things out of our control. Will try to update here when we have a better idea.

**Comment by jberrytech** [comment]
Sprint planning update: Awaiting resolution for NEP. @austinabell will provide more detail.

**Comment by jberrytech** [comment]
@jberrytech organizing a formal tech review.
