### ISSUE TITLE
5.0 tracking issue

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#946]
Just pre-emptively marking issues that would need to wait until a breaking release to be included.

When the list has sufficient motivation, we can bring the changes in and start cutting pre-releases for it.

- [x] #945 
- [x] #1105
- [ ] ~#947~ (probably will solve it in 6.x)
- [ ] ~#749~ (it is not a breaking change, so we can introduce it in 5.1+)
- [x] #1005 (switch from a deprecation warning to compilation error)
- [x] #1034
- [x] #1040 
- [x] #1104
- [x] Upgrade nearcore near-* crates to the 0.19+

**Comment by itegulov** [comment]
We can also include https://github.com/near/near-sdk-rs/issues/749

**Comment by austinabell** [comment]
> We can also include #749

Good point! Feel free to update the issue description directly if you remember any others :)

**Comment by frol** [comment]
Just FYI, I have updated the list and prepared 5.0.0-alpha.1 release: #1070
